import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { Nav } from '@/components/shared/nav';
import { Footer } from '@/components/shared/footer';
import { Toaster } from 'sonner';

const montserrat = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Türk Dünyası Gençlik Topluluğu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Nav />
        {children}
        <Toaster position="top-center" richColors />
        <Footer />
      </body>
    </html>
  );
}
